### ISSUE TITLE
Unable to access without trailing slash.

### ISSUE THREAD

**Issue by junzhengca** [wolfbeacon/wolfbeacon-apidoc-gen#1]
`docs/` will work, however `docs` will not.

The problem is caused by using relative path to reference resources. A quick fix will be redirect `docs` to `docs/`.

**Comment by bholagabbar** [comment]
@junthehacker Could you deploy the app again? I've switched to our own node server which serves the docs at the root url itself, nothing fancy

**Comment by bholagabbar** [comment]
Resolved when we switched to our own http server and serve-static which serves it at the root instead of /docs
