### ISSUE TITLE
Create Hackathon Table

### ISSUE THREAD

**Issue by ralph-dev** [wolfbeacon/wolfbeacon-apidoc-gen#3]
The documentation says a JSON object but doesn't specify the structure of the JSON objects or the fields inside? Let's refer to this: https://wolfbeacon.atlassian.net/wiki/spaces/WC/pages/33390628/Hackathon+Object+Request

**Comment by bholagabbar** [comment]
Still to implement this.

**Comment by bholagabbar** [comment]
Move to Jira
