### ISSUE TITLE
JSON information should be clearly specified (The Structure)

### ISSUE THREAD

**Issue by ralph-dev** [wolfbeacon/wolfbeacon-apidoc-gen#4]
https://api.wolfbeacon.com/docs/#api-Hackathons-CreateHackathon

For these specifically,
bus_routes | json | Bus Routes in travel arrangements
timetable | json | Timetable of hackathon events and happenings
sponsors | json | Sponsors
judges | json | Judges
speakers | json | Speakers
prizes | json | Prizes

Note* Everytime JSON appears the JSON structure should be clearly stated.

**Comment by bholagabbar** [comment]
Move to Jira
